<?php

/*********************************************************************
* Extension configuration file for ext "svconnector_sql".
*
* Generated by ext 02-05-2016 11:37 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Connector service - SQL',
  'description' => 'Connector service for any SQL-based database via ADODB.',
  'category' => 'services',
  'author' => 'Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'author_company' => '',
  'version' => '2.0.0',
  'constraints' =>
  array (
    'depends' =>
    array (
      'typo3' => '7.6.0-8.99.99',
      'svconnector' => '3.0.0-0.0.0',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  '_md5_values_when_last_written' => 'a:17:{s:9:"ChangeLog";s:4:"22c4";s:11:"LICENSE.txt";s:4:"6404";s:10:"README.txt";s:4:"945c";s:13:"composer.json";s:4:"93ef";s:21:"ext_conf_template.txt";s:4:"3fd7";s:12:"ext_icon.png";s:4:"0a7d";s:17:"ext_localconf.php";s:4:"4ac2";s:32:"Classes/Service/ConnectorSql.php";s:4:"eacb";s:26:"Documentation/Includes.txt";s:4:"c83c";s:23:"Documentation/Index.rst";s:4:"1394";s:25:"Documentation/Targets.rst";s:4:"cc7b";s:37:"Documentation/Configuration/Index.rst";s:4:"5236";s:33:"Documentation/Developer/Index.rst";s:4:"3fbc";s:36:"Documentation/Installation/Index.rst";s:4:"0547";s:36:"Documentation/Introduction/Index.rst";s:4:"b8dd";s:40:"Resources/Private/Language/locallang.xlf";s:4:"d004";s:42:"Resources/Public/Samples/Configuration.txt";s:4:"74ed";}',
  'comment' => 'Verified compatibility with TYPO3 CMS 7; moved to namespaces.',
  'user' => 'francois',
);

?>