# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cobweb\SvconnectorSql\:
    resource: '../Classes/*'

  Cobweb\SvconnectorSql\Service\ConnectorSql:
    public: true
    arguments:
      - !tagged_iterator connector.service
